# Generated by Django 5.0.3 on 2024-03-31 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_heroconfig_rename_galery_product_gallery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_subtitle', models.CharField(max_length=255)),
                ('hero_image', models.ImageField(default='placeholder.png', upload_to='hero/')),
            ],
            options={
                'verbose_name_plural': 'Website configuration',
            },
        ),
        migrations.DeleteModel(
            name='HeroConfig',
        ),
    ]
