# Generated by Django 5.0.3 on 2024-04-06 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_websiteconfig_about_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='productgallery',
            old_name='image',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='websiteconfig',
            name='about_text',
        ),
    ]
