# Generated by Django 5.0.3 on 2024-04-06 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_image_product_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='productgallery',
            old_name='img',
            new_name='image',
        ),
    ]
