# Generated by Django 5.0.3 on 2024-04-06 19:13

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_websiteconfig_about_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteconfig',
            name='about_text',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
