# Generated by Django 5.0.3 on 2024-04-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_websiteconfig_about_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteconfig',
            name='about_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
