# Generated by Django 5.0.3 on 2024-04-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_websiteconfig_about_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.FileField(default='files/pdf-placeholder.pdf', upload_to='files/'),
        ),
    ]
