name: Send Backend Content to Server

on:
  push:
    branches:
      - cicd-test

jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install rsync
      run: sudo apt-get install rsync -y

    - name: Sync Backend to Server
      run: rsync -avz -e "ssh -p ${{ secrets.PORT }}" backend/ ${{ secrets.USER }}@${{ secrets.HOST }}:/path/to/destination/backend/
