name: Build and Deploy Backend

on:
  push:
    branches:
      - cicd-test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add .env file
      run: |
        echo "${{ secrets.ENV_BACKEND }}" > ./backend/.env
      shell: bash

    - name: Create SSH private key file
      run: echo "$SSH_PRIVATE_KEY" > ./ssh-private-key
      shell: bash

    - name: Deploy backend via SCP
      run: |
        scp -o StrictHostKeyChecking=no -r -P 10131 -i ./ssh-private-key ./backend/* root@srv26.mikr.us:ecommerce/backend
      shell: bash

    - name: Deploy backend via SSH
      run: |
        ssh -o StrictHostKeyChecking=no -p 10131 -i ./ssh-private-key root@srv26.mikr.us 'bash -s' < ~/ecommerce/backend/deploy.sh
