name: Deploy Backend to Server

on:
  push:
    branches:
      - cicd-test

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Deploy Backend
      run: |
        scp -P ${{ secrets.PORT }} backend/* ${{ secrets.USER }}@${{ secrets.HOST }}:/app/backend
