name: Deploy Backend to Server

on:
  push:
    branches:
      - cicd-test

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Deploy Backend
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key.pem
        chmod 600 ssh_key.pem
        scp -i ssh_key.pem -P ${{ secrets.PORT }} backend/* ${{ secrets.USER }}@${{ secrets.HOST }}:/app/backend
      shell: bash
